# Generated by Django 2.2.6 on 2019-10-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=250)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=100)),
                ('ncm', models.CharField(max_length=50)),
                ('icms', models.CharField(max_length=2)),
                ('ip', models.CharField(max_length=3)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Categoria')),
            ],
        ),
    ]
