# Generated by Django 2.2.6 on 2019-10-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='src',
            field=models.CharField(default='teste', max_length=250),
            preserve_default=False,
        ),
    ]
