# Generated by Django 2.2.6 on 2019-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='src',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
