# Generated by Django 2.2.6 on 2019-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_sefaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='src',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
